[env:bluepill_f103c8]
platform  = ststm32
board     = bluepill_f103c8
framework = arduino

monitor_speed = 115200

; I2C 與 Serial 使用預設腳位：
;   I2C1  : SCL = PB6, SDA = PB7
;   USART1: TX  = PA9, RX  = PA10  (Serial 預設)
build_flags =
    -DSERIAL_UART_INSTANCE=1
